//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatToWatch {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatToWatch.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        internal static string Actors {
            get {
                return ResourceManager.GetString("Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to fill all the fields.
        /// </summary>
        internal static string AllFieldsAreRequired {
            get {
                return ResourceManager.GetString("AllFieldsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution!.
        /// </summary>
        internal static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose criterias.
        /// </summary>
        internal static string ChooseCriterias {
            get {
                return ResourceManager.GetString("ChooseCriterias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments found.
        /// </summary>
        internal static string CommentsFound {
            get {
                return ResourceManager.GetString("CommentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue....
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue voting.
        /// </summary>
        internal static string ContinueVoting {
            get {
                return ResourceManager.GetString("ContinueVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotions.
        /// </summary>
        internal static string Emotions {
            get {
                return ResourceManager.GetString("Emotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite movies.
        /// </summary>
        internal static string FavoritesCount {
            get {
                return ResourceManager.GetString("FavoritesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor.
        /// </summary>
        internal static string FavoritesTab {
            get {
                return ResourceManager.GetString("FavoritesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get recommendations.
        /// </summary>
        internal static string GetRecommendations {
            get {
                return ResourceManager.GetString("GetRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server answer.
        /// </summary>
        internal static string InvalidServerAnswer {
            get {
                return ResourceManager.GetString("InvalidServerAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log in for adding to favorites.
        /// </summary>
        internal static string LogInForAddingToFavorites {
            get {
                return ResourceManager.GetString("LogInForAddingToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to see your favorites.
        /// </summary>
        internal static string LogInForFavoritesList {
            get {
                return ResourceManager.GetString("LogInForFavoritesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in for being able to get recommendations.
        /// </summary>
        internal static string LogInForRecommendations {
            get {
                return ResourceManager.GetString("LogInForRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log in for voting.
        /// </summary>
        internal static string LogInForVoting {
            get {
                return ResourceManager.GetString("LogInForVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LoginTab {
            get {
                return ResourceManager.GetString("LoginTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log in to add a comment.
        /// </summary>
        internal static string LogInToComment {
            get {
                return ResourceManager.GetString("LogInToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message!.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message was sent to your e-mail for sign up confirmation.
        /// </summary>
        internal static string MessageSentToEmail {
            get {
                return ResourceManager.GetString("MessageSentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies found.
        /// </summary>
        internal static string MoviesFound {
            get {
                return ResourceManager.GetString("MoviesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies not found.
        /// </summary>
        internal static string MoviesNotFound {
            get {
                return ResourceManager.GetString("MoviesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New movies.
        /// </summary>
        internal static string NewMovies {
            get {
                return ResourceManager.GetString("NewMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments found.
        /// </summary>
        internal static string NoCommentsFound {
            get {
                return ResourceManager.GetString("NoCommentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t added any movie to favorites yet.
        /// </summary>
        internal static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t entered login and/or password.
        /// </summary>
        internal static string NoLoginOrPassword {
            get {
                return ResourceManager.GetString("NoLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation criterias.
        /// </summary>
        internal static string RecommendationCriterias {
            get {
                return ResourceManager.GetString("RecommendationCriterias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recom.
        /// </summary>
        internal static string RecommendationTab {
            get {
                return ResourceManager.GetString("RecommendationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchTab {
            get {
                return ResourceManager.GetString("SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Voting.
        /// </summary>
        internal static string StopVoting {
            get {
                return ResourceManager.GetString("StopVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voted.
        /// </summary>
        internal static string Voted {
            get {
                return ResourceManager.GetString("Voted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to get recommendations you need to vote at least 10 movies by all the criterias. You can search movies for voting by yourself or we can propose a random movie for you.
        /// </summary>
        internal static string VoteMoviesBeforeRecommendations {
            get {
                return ResourceManager.GetString("VoteMoviesBeforeRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote a random movie.
        /// </summary>
        internal static string VoteRandomMovie {
            get {
                return ResourceManager.GetString("VoteRandomMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve voted minimal required number of movies. Now you can get recommendations.
        /// </summary>
        internal static string VotingFinished {
            get {
                return ResourceManager.GetString("VotingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t voted minimal required number of movies.
        /// </summary>
        internal static string VotingNotFinished {
            get {
                return ResourceManager.GetString("VotingNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
